// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Components__DrawerComponentController from "./components/drawer_component_controller"
application.register("components--drawer-component", Components__DrawerComponentController)

import Components__FlashController from "./components/flash_controller"
application.register("components--flash", Components__FlashController)

import PreviewsController from "./previews_controller"
application.register("previews", PreviewsController)

import SearchController from "./search_controller"
application.register("search", SearchController)
